// Bundles core/index.ts → pb_hooks/lib/core.js (CommonJS for PocketBase's
// JS runtime). `--check` fails when the committed bundle is out of date.
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "pb_hooks/lib/core.js");

const result = await build({
  entryPoints: [join(root, "core/index.ts")],
  bundle: true,
  format: "cjs",
  platform: "neutral",
  target: "es2019",
  write: false,
  legalComments: "none",
  banner: { js: "// GENERATED by scripts/build-core.mjs from firebase/functions/src — do not edit." },
});
const code = result.outputFiles[0].text;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(out, "utf8");
  } catch {}
  if (current !== code) {
    console.error("pb_hooks/lib/core.js is stale — run `npm run build:core`.");
    process.exit(1);
  }
  console.log("core.js up to date");
} else {
  writeFileSync(out, code);
  console.log(`wrote ${out} (${code.length} bytes)`);
}
