// GENERATED by scripts/build-core.mjs from firebase/functions/src — do not edit.
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// core/index.ts
var index_exports = {};
__export(index_exports, {
  ACTIVE_TICKET_STATUSES: () => ACTIVE_TICKET_STATUSES,
  ASSIGNABLE_ROLES: () => ASSIGNABLE_ROLES,
  DEFAULT_SETTINGS: () => DEFAULT_SETTINGS,
  PERMISSIONS: () => PERMISSIONS,
  ROLES: () => ROLES,
  ROLE_PERMISSIONS: () => ROLE_PERMISSIONS,
  ROLE_TIER: () => ROLE_TIER,
  ROOM_TRANSITIONS: () => ROOM_TRANSITIONS,
  can: () => can,
  canAssign: () => canAssign,
  computeDailyMetrics: () => computeDailyMetrics,
  generateInsights: () => generateInsights,
  isActiveTicket: () => isActiveTicket,
  isRole: () => isRole,
  isValidNationalId: () => isValidNationalId,
  maskNationalId: () => maskNationalId,
  normalizeNationalId: () => normalizeNationalId,
  rolesWith: () => rolesWith
});
module.exports = __toCommonJS(index_exports);

// ../firebase/functions/src/domain/rbac.ts
var ROLES = [
  "superAdmin",
  "hotelOwner",
  "generalManager",
  "operationsManager",
  "energyManager",
  "maintenanceManager",
  "housekeepingManager",
  "restaurantManager",
  "inventoryManager",
  "hrManager",
  "receptionStaff",
  "housekeepingStaff",
  "maintenanceStaff",
  "restaurantStaff",
  "analyst"
];
var PERMISSIONS = [
  "dashboard.executive",
  "dashboard.operations",
  "rooms.view",
  "rooms.updateStatus",
  "rooms.manage",
  "housekeeping.viewOwn",
  "housekeeping.viewAll",
  "housekeeping.assign",
  "housekeeping.complete",
  "maintenance.report",
  "maintenance.viewOwn",
  "maintenance.viewAll",
  "maintenance.manage",
  "maintenance.work",
  "energy.view",
  "energy.record",
  "inventory.view",
  "inventory.move",
  "inventory.manage",
  "staff.viewOwnShifts",
  "staff.view",
  "staff.manage",
  "operations.recordDaily",
  "finance.view",
  "reports.view",
  "reports.generate",
  "notifications.view",
  "ai.insights.view",
  "ai.assistant.use",
  "users.manage",
  "audit.view",
  "hotel.settings"
];
var STAFF_COMMON = [
  "maintenance.report",
  "maintenance.viewOwn",
  "staff.viewOwnShifts",
  "notifications.view"
];
var ROLE_PERMISSIONS = {
  superAdmin: PERMISSIONS,
  hotelOwner: [
    "dashboard.executive",
    "rooms.view",
    "housekeeping.viewAll",
    "maintenance.report",
    "maintenance.viewAll",
    "energy.view",
    "inventory.view",
    "staff.view",
    "finance.view",
    "reports.view",
    "reports.generate",
    "notifications.view",
    "ai.insights.view",
    "ai.assistant.use",
    "users.manage",
    "audit.view",
    "hotel.settings"
  ],
  generalManager: [
    "dashboard.executive",
    "dashboard.operations",
    "rooms.view",
    "rooms.updateStatus",
    "rooms.manage",
    "housekeeping.viewAll",
    "housekeeping.assign",
    "maintenance.report",
    "maintenance.viewAll",
    "maintenance.manage",
    "energy.view",
    "energy.record",
    "inventory.view",
    "inventory.move",
    "inventory.manage",
    "staff.view",
    "staff.manage",
    "operations.recordDaily",
    "finance.view",
    "reports.view",
    "reports.generate",
    "notifications.view",
    "ai.insights.view",
    "ai.assistant.use",
    "users.manage",
    "audit.view",
    "hotel.settings"
  ],
  operationsManager: [
    "dashboard.operations",
    "rooms.view",
    "rooms.updateStatus",
    "rooms.manage",
    "housekeeping.viewAll",
    "housekeeping.assign",
    "maintenance.report",
    "maintenance.viewAll",
    "maintenance.manage",
    "energy.view",
    "inventory.view",
    "staff.view",
    "staff.manage",
    "operations.recordDaily",
    "reports.view",
    "reports.generate",
    "notifications.view",
    "ai.insights.view",
    "ai.assistant.use"
  ],
  energyManager: [
    "dashboard.operations",
    "rooms.view",
    "energy.view",
    "energy.record",
    "maintenance.report",
    "maintenance.viewAll",
    "reports.view",
    "reports.generate",
    "notifications.view",
    "ai.insights.view",
    "ai.assistant.use"
  ],
  maintenanceManager: [
    "dashboard.operations",
    "rooms.view",
    "rooms.updateStatus",
    "maintenance.report",
    "maintenance.viewAll",
    "maintenance.manage",
    "maintenance.work",
    "energy.view",
    "inventory.view",
    "inventory.move",
    "staff.view",
    "reports.view",
    "reports.generate",
    "notifications.view",
    "ai.insights.view"
  ],
  housekeepingManager: [
    "dashboard.operations",
    "rooms.view",
    "rooms.updateStatus",
    "housekeeping.viewAll",
    "housekeeping.assign",
    "housekeeping.complete",
    "maintenance.report",
    "maintenance.viewOwn",
    "inventory.view",
    "inventory.move",
    "staff.view",
    "reports.view",
    "notifications.view",
    "ai.insights.view"
  ],
  restaurantManager: [
    "dashboard.operations",
    "inventory.view",
    "inventory.move",
    "maintenance.report",
    "maintenance.viewOwn",
    "staff.view",
    "reports.view",
    "notifications.view",
    "ai.insights.view"
  ],
  inventoryManager: [
    "dashboard.operations",
    "inventory.view",
    "inventory.move",
    "inventory.manage",
    "maintenance.report",
    "maintenance.viewOwn",
    "reports.view",
    "reports.generate",
    "notifications.view",
    "ai.insights.view"
  ],
  hrManager: [
    "dashboard.operations",
    "staff.view",
    "staff.manage",
    "users.manage",
    "maintenance.report",
    "maintenance.viewOwn",
    "reports.view",
    "notifications.view"
  ],
  receptionStaff: [...STAFF_COMMON, "rooms.view", "rooms.updateStatus", "operations.recordDaily"],
  housekeepingStaff: [
    ...STAFF_COMMON,
    "rooms.view",
    "rooms.updateStatus",
    "housekeeping.viewOwn",
    "housekeeping.complete"
  ],
  maintenanceStaff: [...STAFF_COMMON, "rooms.view", "maintenance.work"],
  restaurantStaff: [...STAFF_COMMON, "inventory.view"],
  analyst: [
    "dashboard.executive",
    "rooms.view",
    "housekeeping.viewAll",
    "maintenance.viewAll",
    "energy.view",
    "inventory.view",
    "staff.view",
    "finance.view",
    "reports.view",
    "reports.generate",
    "notifications.view",
    "ai.insights.view",
    "ai.assistant.use"
  ]
};
var ASSIGNABLE_ROLES = {
  superAdmin: ROLES,
  hotelOwner: ROLES.filter((r) => r !== "superAdmin" && r !== "hotelOwner"),
  generalManager: ROLES.filter(
    (r) => r !== "superAdmin" && r !== "hotelOwner" && r !== "generalManager"
  ),
  hrManager: ["receptionStaff", "housekeepingStaff", "maintenanceStaff", "restaurantStaff"]
};
var ROLE_TIER = {
  superAdmin: "platform",
  hotelOwner: "executive",
  generalManager: "executive",
  analyst: "executive",
  operationsManager: "manager",
  energyManager: "manager",
  maintenanceManager: "manager",
  housekeepingManager: "manager",
  restaurantManager: "manager",
  inventoryManager: "manager",
  hrManager: "manager",
  receptionStaff: "staff",
  housekeepingStaff: "staff",
  maintenanceStaff: "staff",
  restaurantStaff: "staff"
};
var ROOM_TRANSITIONS = {
  housekeepingStaff: {
    vacantDirty: ["cleaningInProgress"],
    cleaningInProgress: ["vacantClean"]
  },
  housekeepingManager: {
    vacantDirty: ["cleaningInProgress", "vacantClean"],
    cleaningInProgress: ["vacantClean", "vacantDirty"],
    vacantClean: ["vacantDirty"],
    outOfOrder: ["vacantDirty"]
  },
  receptionStaff: {
    vacantClean: ["occupied"],
    occupied: ["vacantDirty"]
  },
  maintenanceManager: {
    vacantClean: ["outOfOrder"],
    vacantDirty: ["outOfOrder"],
    outOfOrder: ["vacantDirty"]
  }
};
function isRole(value) {
  return typeof value === "string" && ROLES.includes(value);
}
function can(role, permission) {
  return ROLE_PERMISSIONS[role].includes(permission);
}
function canAssign(actor, target) {
  var _a;
  return ((_a = ASSIGNABLE_ROLES[actor]) != null ? _a : []).includes(target);
}
function rolesWith(permission) {
  return ROLES.filter((r) => r !== "superAdmin" && can(r, permission));
}

// ../firebase/functions/src/domain/national-id.ts
var PERSIAN = "\u06F0\u06F1\u06F2\u06F3\u06F4\u06F5\u06F6\u06F7\u06F8\u06F9";
var ARABIC = "\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669";
function normalizeNationalId(input) {
  let out = "";
  for (const ch of input) {
    if (ch.trim() === "" || ch === "-") continue;
    const p = PERSIAN.indexOf(ch);
    const a = ARABIC.indexOf(ch);
    out += p >= 0 ? String(p) : a >= 0 ? String(a) : ch;
  }
  return out;
}
function isValidNationalId(input) {
  const v = normalizeNationalId(input);
  if (!/^\d{10}$/.test(v) || /^(\d)\1{9}$/.test(v)) return false;
  const digits = [...v].map(Number);
  let sum = 0;
  for (let i = 0; i < 9; i++) sum += digits[i] * (10 - i);
  const r = sum % 11;
  return (r < 2 ? r : 11 - r) === digits[9];
}
function maskNationalId(input) {
  const v = normalizeNationalId(input);
  return v.length === 10 ? `${v.slice(0, 3)}\u2022\u2022\u2022\u2022\u2022${v.slice(8)}` : v;
}

// ../firebase/functions/src/analytics/types.ts
var DEFAULT_SETTINGS = {
  energyDailyBaseline: { electricity: 2400, water: 38, gas: 310 },
  energyTariff: { electricity: 3200, water: 21e3, gas: 4100 },
  energyAlertThresholdPct: 15,
  maintenanceSlaHours: { critical: 2, high: 8, medium: 24, low: 72 },
  targetCleanMinutes: { checkoutClean: 35, stayoverClean: 20, deepClean: 90, inspection: 10, turndown: 10 }
};
var ACTIVE_TICKET_STATUSES = ["open", "assigned", "inProgress", "onHold"];
function isActiveTicket(t) {
  return ACTIVE_TICKET_STATUSES.includes(t.status);
}

// ../firebase/functions/src/analytics/metrics.ts
var round = (v, d = 2) => Math.round(v * 10 ** d) / 10 ** d;
function computeDailyMetrics(input) {
  var _a, _b, _c, _d, _e, _f, _g, _h;
  const { day, settings, operations: ops } = input;
  const energyOf = (type) => {
    const rows = input.energy.filter((e) => e.day === day && e.type === type);
    return rows.length === 0 ? null : rows.reduce((s, r) => s + r.consumption, 0);
  };
  const electricity = energyOf("electricity");
  const water = energyOf("water");
  const gas = energyOf("gas");
  const energyCost = (electricity != null ? electricity : 0) * ((_a = settings.energyTariff.electricity) != null ? _a : 0) + (water != null ? water : 0) * ((_b = settings.energyTariff.water) != null ? _b : 0) + (gas != null ? gas : 0) * ((_c = settings.energyTariff.gas) != null ? _c : 0);
  const baseline = (_d = settings.energyDailyBaseline.electricity) != null ? _d : 0;
  const active = input.tickets.filter(isActiveTicket);
  const resolvedOnDay = input.tickets.filter(
    (t) => t.resolvedAt && input.dayKeyOf(t.resolvedAt) === day
  );
  const resolutionHours = input.tickets.filter((t) => t.resolvedAt).map((t) => (t.resolvedAt.getTime() - t.createdAt.getTime()) / 36e5);
  const dayTasks = input.tasks.filter((t) => t.day === day && t.status !== "cancelled");
  const cleanMinutes = dayTasks.filter((t) => t.type === "checkoutClean" && t.status === "done" && t.startedAt && t.completedAt).map((t) => (t.completedAt.getTime() - t.startedAt.getTime()) / 6e4);
  return {
    day,
    occupancyRate: ops && ops.roomsAvailable > 0 ? round(ops.roomsOccupied / ops.roomsAvailable * 100) : null,
    roomsOccupied: (_e = ops == null ? void 0 : ops.roomsOccupied) != null ? _e : null,
    roomsAvailable: (_f = ops == null ? void 0 : ops.roomsAvailable) != null ? _f : null,
    adr: ops && ops.roomsOccupied > 0 ? round(ops.roomRevenue / ops.roomsOccupied, 0) : null,
    revpar: ops && ops.roomsAvailable > 0 ? round(ops.roomRevenue / ops.roomsAvailable, 0) : null,
    totalRevenue: ops ? ops.roomRevenue + ((_g = ops.fnbRevenue) != null ? _g : 0) + ((_h = ops.otherRevenue) != null ? _h : 0) : null,
    energy: { electricity, water, gas },
    energyCost: round(energyCost, 0),
    electricityPerOccupiedRoom: electricity != null && ops && ops.roomsOccupied > 0 ? round(electricity / ops.roomsOccupied) : null,
    electricityVsBaselinePct: electricity != null && baseline > 0 ? round((electricity - baseline) / baseline * 100, 1) : null,
    maintenance: {
      open: active.length,
      overdue: active.filter((t) => t.slaDueAt && t.slaDueAt < input.now).length,
      critical: active.filter((t) => t.priority === "critical").length,
      createdOnDay: input.tickets.filter((t) => input.dayKeyOf(t.createdAt) === day).length,
      resolvedOnDay: resolvedOnDay.length,
      avgResolutionHours: resolutionHours.length === 0 ? null : round(resolutionHours.reduce((a, b) => a + b, 0) / resolutionHours.length, 1)
    },
    housekeeping: {
      tasks: dayTasks.length,
      done: dayTasks.filter((t) => t.status === "done").length,
      avgCheckoutCleanMinutes: cleanMinutes.length === 0 ? null : round(cleanMinutes.reduce((a, b) => a + b, 0) / cleanMinutes.length, 1)
    },
    inventory: {
      lowStock: input.items.filter((i) => i.quantity <= i.reorderLevel).length,
      outOfStock: input.items.filter((i) => i.quantity <= 0).length,
      stockValue: round(input.items.reduce((s, i) => {
        var _a2;
        return s + i.quantity * ((_a2 = i.unitCost) != null ? _a2 : 0);
      }, 0), 0)
    },
    rooms: {
      outOfOrder: input.rooms.filter((r) => r.status === "outOfOrder").length,
      total: input.rooms.length
    },
    version: 1
  };
}

// ../firebase/functions/src/analytics/rules-engine.ts
var fmt = (v, d = 0) => {
  const fixed = Math.abs(v).toFixed(d);
  const [int, frac] = fixed.split(".");
  const sign = v < 0 && Number(fixed) !== 0 ? "-" : "";
  return sign + int.replace(/\B(?=(\d{3})+(?!\d))/g, ",") + (frac ? `.${frac}` : "");
};
function generateInsights(input) {
  return [
    ...energyIntensityRule(input),
    ...stockoutForecastRule(input),
    ...housekeepingEfficiencyRule(input),
    ...repeatFailureRule(input),
    ...outOfOrderRevenueRule(input),
    ...weekdayOccupancyRule(input)
  ];
}
function sumBy(rows, f) {
  return rows.reduce((s, r) => s + f(r), 0);
}
function energyIntensityRule(input) {
  var _a;
  const { today, addDays } = input;
  const recentDays = [1, 2, 3, 4].map((d) => addDays(today, -d));
  const priorDays = Array.from({ length: 21 }, (_, i) => addDays(today, -(i + 5)));
  const intensity = (days) => {
    let kwh = 0;
    let occ = 0;
    let n = 0;
    for (const day of days) {
      const e = input.energy.filter((r) => r.day === day && r.type === "electricity");
      const o = input.operations.find((r) => r.day === day);
      if (e.length === 0 || !o || o.roomsOccupied === 0) continue;
      kwh += sumBy(e, (r) => r.consumption);
      occ += o.roomsOccupied;
      n++;
    }
    return { perRoom: occ === 0 ? null : kwh / occ, avgKwh: n === 0 ? 0 : kwh / n, avgOcc: n === 0 ? 0 : occ / n, n };
  };
  const recent = intensity(recentDays);
  const prior = intensity(priorDays);
  if (recent.perRoom == null || prior.perRoom == null || recent.n < 3 || prior.n < 7) return [];
  const change = (recent.perRoom - prior.perRoom) / prior.perRoom;
  const occChange = prior.avgOcc === 0 ? 0 : (recent.avgOcc - prior.avgOcc) / prior.avgOcc;
  if (change < 0.12 || Math.abs(occChange) > 0.08) return [];
  const hvac = input.tickets.filter((t) => isActiveTicket(t) && t.category === "hvac");
  const extraKwhPerDay = (recent.perRoom - prior.perRoom) * recent.avgOcc;
  const saving = extraKwhPerDay * 30 * ((_a = input.settings.energyTariff.electricity) != null ? _a : 0);
  return [
    {
      id: "energyIntensity_electricity",
      rule: "energyIntensity",
      category: "energy",
      title: `\u0627\u0641\u0632\u0627\u06CC\u0634 ${fmt(change * 100)}\u066A \u0634\u062F\u062A \u0645\u0635\u0631\u0641 \u0628\u0631\u0642 \u0628\u062F\u0648\u0646 \u062A\u063A\u06CC\u06CC\u0631 \u0627\u0634\u063A\u0627\u0644`,
      summary: `\u0645\u0635\u0631\u0641 \u0628\u0631\u0642 \u0628\u0647 \u0627\u0632\u0627\u06CC \u0647\u0631 \u0627\u062A\u0627\u0642 \u0627\u0634\u063A\u0627\u0644\u200C\u0634\u062F\u0647 \u0627\u0632 ${fmt(prior.perRoom, 1)} \u0628\u0647 ${fmt(recent.perRoom, 1)} \u06A9\u06CC\u0644\u0648\u0648\u0627\u062A\u200C\u0633\u0627\u0639\u062A \u0631\u0633\u06CC\u062F\u0647\u060C \u062F\u0631 \u062D\u0627\u0644\u06CC \u06A9\u0647 \u0646\u0631\u062E \u0627\u0634\u063A\u0627\u0644 ${fmt(occChange * 100)}\u066A \u062A\u063A\u06CC\u06CC\u0631 \u06A9\u0631\u062F\u0647 \u0627\u0633\u062A.` + (hvac.length > 0 ? ` ${hvac.length} \u062A\u06CC\u06A9\u062A \u0628\u0627\u0632 HVAC \u0648\u062C\u0648\u062F \u062F\u0627\u0631\u062F (\xAB${hvac[0].title}\xBB).` : ""),
      recommendation: hvac.length > 0 ? "\u0633\u0631\u0648\u06CC\u0633 \u0641\u0648\u0631\u06CC \u062A\u062C\u0647\u06CC\u0632\u0627\u062A HVAC \u0645\u0631\u062A\u0628\u0637 \u0628\u0627 \u062A\u06CC\u06A9\u062A\u200C\u0647\u0627\u06CC \u0628\u0627\u0632 \u0648 \u062A\u0646\u0638\u06CC\u0645 \u0646\u0642\u0637\u0647 \u06A9\u0627\u0631 \u0633\u0631\u0645\u0627\u06CC\u0634/\u06AF\u0631\u0645\u0627\u06CC\u0634 \u0627\u062A\u0627\u0642\u200C\u0647\u0627\u06CC \u062E\u0627\u0644\u06CC." : "\u0628\u0627\u0632\u0631\u0633\u06CC \u0645\u0635\u0631\u0641\u200C\u06A9\u0646\u0646\u062F\u0647\u200C\u0647\u0627\u06CC \u0628\u0632\u0631\u06AF (\u0686\u06CC\u0644\u0631\u060C \u0628\u0648\u06CC\u0644\u0631\u060C \u067E\u0645\u067E\u200C\u0647\u0627) \u0648 \u062A\u0646\u0638\u06CC\u0645 \u0633\u0631\u0645\u0627\u06CC\u0634/\u06AF\u0631\u0645\u0627\u06CC\u0634 \u0627\u062A\u0627\u0642\u200C\u0647\u0627\u06CC \u062E\u0627\u0644\u06CC.",
      confidence: hvac.length > 0 ? 0.82 : 0.66,
      priority: change > 0.2 ? "high" : "medium",
      estimatedMonthlySaving: Math.round(saving),
      evidence: [
        `\u0634\u062F\u062A \u0645\u0635\u0631\u0641 \u06F4 \u0631\u0648\u0632 \u0627\u062E\u06CC\u0631: ${fmt(recent.perRoom, 1)} kWh/\u0627\u062A\u0627\u0642`,
        `\u0634\u062F\u062A \u0645\u0635\u0631\u0641 \u06F2\u06F1 \u0631\u0648\u0632 \u0642\u0628\u0644: ${fmt(prior.perRoom, 1)} kWh/\u0627\u062A\u0627\u0642`,
        `\u0645\u06CC\u0627\u0646\u06AF\u06CC\u0646 \u0627\u062A\u0627\u0642 \u0627\u0634\u063A\u0627\u0644: ${fmt(recent.avgOcc)} \u062F\u0631 \u0628\u0631\u0627\u0628\u0631 ${fmt(prior.avgOcc)}`,
        ...hvac.length > 0 ? [`\u062A\u06CC\u06A9\u062A\u200C\u0647\u0627\u06CC \u0628\u0627\u0632 HVAC: ${hvac.length}`] : []
      ],
      route: "/energy",
      audienceRoles: ["generalManager", "energyManager", "maintenanceManager"]
    }
  ];
}
function stockoutForecastRule(input) {
  var _a;
  const since = new Date(input.now.getTime() - 14 * 864e5);
  const out = [];
  for (const item of input.items) {
    const issued = input.movements.filter((m) => m.itemId === item.id && m.createdAt >= since && (m.type === "issue" || m.type === "waste")).reduce((s, m) => s + Math.abs(m.delta), 0);
    const perDay = issued / 14;
    if (perDay <= 0) continue;
    const daysLeft = item.quantity / perDay;
    if (daysLeft > 5) continue;
    const order = Math.ceil(Math.max((_a = item.reorderQuantity) != null ? _a : 0, perDay * 14));
    out.push({
      id: `stockout_${item.id}`,
      rule: "stockout",
      category: "inventory",
      title: `\u067E\u06CC\u0634\u200C\u0628\u06CC\u0646\u06CC \u0627\u062A\u0645\u0627\u0645 \xAB${item.name}\xBB \u062A\u0627 ${fmt(Math.max(daysLeft, 0))} \u0631\u0648\u0632 \u0622\u06CC\u0646\u062F\u0647`,
      summary: `\u0645\u0635\u0631\u0641 \u0631\u0648\u0632\u0627\u0646\u0647 \u062D\u062F\u0648\u062F ${fmt(perDay, 1)} ${item.unit} \u0648 \u0645\u0648\u062C\u0648\u062F\u06CC \u0641\u0639\u0644\u06CC ${fmt(item.quantity)} ${item.unit} \u0627\u0633\u062A.`,
      recommendation: `\u062B\u0628\u062A \u0633\u0641\u0627\u0631\u0634 ${fmt(order)} ${item.unit} \u0627\u0645\u0631\u0648\u0632.`,
      confidence: 0.85,
      priority: daysLeft < 2 ? "high" : "medium",
      evidence: [
        `\u0645\u0648\u062C\u0648\u062F\u06CC: ${fmt(item.quantity)} ${item.unit}`,
        `\u0646\u0642\u0637\u0647 \u0633\u0641\u0627\u0631\u0634: ${fmt(item.reorderLevel)}`,
        `\u0645\u0635\u0631\u0641 \u06F1\u06F4 \u0631\u0648\u0632: ${fmt(issued)} ${item.unit}`
      ],
      route: `/inventory/${item.id}`,
      audienceRoles: ["inventoryManager", "generalManager"]
    });
  }
  return out;
}
function housekeepingEfficiencyRule(input) {
  var _a;
  const target = (_a = input.settings.targetCleanMinutes.checkoutClean) != null ? _a : 35;
  const window = new Set(Array.from({ length: 7 }, (_, i) => input.addDays(input.today, -i)));
  const durations = input.tasks.filter((t) => window.has(t.day) && t.type === "checkoutClean" && t.status === "done" && t.startedAt && t.completedAt).map((t) => (t.completedAt.getTime() - t.startedAt.getTime()) / 6e4);
  if (durations.length < 5) return [];
  const avg = durations.reduce((a, b) => a + b, 0) / durations.length;
  const over = (avg - target) / target;
  if (over < 0.15) return [];
  const lostHoursPerWeek = (avg - target) * durations.length / 60;
  return [
    {
      id: "hkEfficiency_checkout",
      rule: "hkEfficiency",
      category: "housekeeping",
      title: `\u0632\u0645\u0627\u0646 \u0646\u0638\u0627\u0641\u062A \u0627\u062A\u0627\u0642\u200C\u0647\u0627\u06CC \u062A\u062E\u0644\u06CC\u0647 ${fmt(over * 100)}\u066A \u0628\u06CC\u0634 \u0627\u0632 \u0647\u062F\u0641`,
      summary: `\u0645\u06CC\u0627\u0646\u06AF\u06CC\u0646 ${fmt(avg)} \u062F\u0642\u06CC\u0642\u0647 \u062F\u0631 \u0628\u0631\u0627\u0628\u0631 \u0647\u062F\u0641 ${fmt(target)} \u062F\u0642\u06CC\u0642\u0647 (${durations.length} \u0646\u0638\u0627\u0641\u062A \u062F\u0631 \u06F7 \u0631\u0648\u0632).`,
      recommendation: "\u0622\u0645\u0627\u062F\u0647\u200C\u0633\u0627\u0632\u06CC \u062A\u0631\u0648\u0644\u06CC \u067E\u06CC\u0634 \u0627\u0632 \u0634\u06CC\u0641\u062A\u060C \u062A\u062E\u0635\u06CC\u0635 \u0627\u062A\u0627\u0642\u200C\u0647\u0627 \u0628\u0631 \u0627\u0633\u0627\u0633 \u0637\u0628\u0642\u0647 \u0648 \u0628\u0631\u0631\u0633\u06CC \u0645\u0648\u0627\u0646\u0639 (\u06A9\u0645\u0628\u0648\u062F \u0645\u0644\u062D\u0641\u0647/\u0627\u0642\u0644\u0627\u0645).",
      confidence: 0.72,
      priority: over > 0.3 ? "high" : "medium",
      evidence: [`\u0633\u0627\u0639\u0627\u062A \u0627\u0636\u0627\u0641\u0647 \u0647\u0641\u062A\u06AF\u06CC: ${fmt(lostHoursPerWeek, 1)}`, `\u0646\u0645\u0648\u0646\u0647\u200C\u0647\u0627: ${durations.length}`],
      route: "/housekeeping",
      audienceRoles: ["housekeepingManager", "operationsManager"]
    }
  ];
}
function repeatFailureRule(input) {
  var _a, _b;
  const since = new Date(input.now.getTime() - 30 * 864e5);
  const groups = /* @__PURE__ */ new Map();
  for (const t of input.tickets.filter((t2) => t2.createdAt >= since)) {
    const where = t.roomNumber ? `room-${t.roomNumber}` : ((_a = t.area) != null ? _a : "").trim();
    if (!where) continue;
    const key = `${t.category}|${where}`;
    groups.set(key, [...(_b = groups.get(key)) != null ? _b : [], t]);
  }
  const out = [];
  for (const [key, list] of groups) {
    if (list.length < 3) continue;
    const [category, where] = key.split("|");
    out.push({
      id: `repeatFailure_${category}_${where}`.replace(/[^\w-]/g, "_"),
      rule: "repeatFailure",
      category: "maintenance",
      title: `${list.length} \u062E\u0631\u0627\u0628\u06CC \u062A\u06A9\u0631\u0627\u0631\u06CC \u062F\u0631 ${where.replace("room-", "\u0627\u062A\u0627\u0642 ")} \u0637\u06CC \u06F3\u06F0 \u0631\u0648\u0632`,
      summary: `\u062F\u0633\u062A\u0647: ${category}. \u062E\u0631\u0627\u0628\u06CC\u200C\u0647\u0627\u06CC \u0645\u06A9\u0631\u0631 \u0646\u0634\u0627\u0646\u0647 \u0646\u06CC\u0627\u0632 \u0628\u0647 \u062A\u0639\u0645\u06CC\u0631 \u0627\u0633\u0627\u0633\u06CC \u06CC\u0627 \u062A\u0639\u0648\u06CC\u0636 \u062A\u062C\u0647\u06CC\u0632 \u0627\u0633\u062A.`,
      recommendation: "\u0628\u0631\u0646\u0627\u0645\u0647\u200C\u0631\u06CC\u0632\u06CC \u0628\u0627\u0632\u062F\u06CC\u062F \u067E\u06CC\u0634\u06AF\u06CC\u0631\u0627\u0646\u0647 \u0648 \u0628\u0631\u0631\u0633\u06CC \u0647\u0632\u06CC\u0646\u0647 \u062A\u0639\u0645\u06CC\u0631 \u062F\u0631 \u0628\u0631\u0627\u0628\u0631 \u062A\u0639\u0648\u06CC\u0636.",
      confidence: 0.7,
      priority: list.length >= 5 ? "high" : "medium",
      evidence: list.slice(0, 5).map((t) => t.title),
      route: "/maintenance",
      audienceRoles: ["maintenanceManager", "generalManager"]
    });
  }
  return out;
}
function outOfOrderRevenueRule(input) {
  const ooo = input.rooms.filter(
    (r) => r.status === "outOfOrder" && r.updatedAt && input.now.getTime() - r.updatedAt.getTime() > 864e5
  );
  if (ooo.length === 0) return [];
  const recent = input.operations.slice(-14);
  const sold = recent.reduce((s, o) => s + o.roomsOccupied, 0);
  const available = recent.reduce((s, o) => s + o.roomsAvailable, 0);
  const revenue = recent.reduce((s, o) => s + o.roomRevenue, 0);
  if (sold === 0 || available === 0) return [];
  const adr = revenue / sold;
  const occ = sold / available;
  const lostPerMonth = ooo.length * adr * occ * 30;
  return [
    {
      id: "outOfOrder_revenue",
      rule: "outOfOrderRevenue",
      category: "revenue",
      title: `${ooo.length} \u0627\u062A\u0627\u0642 \u0628\u06CC\u0634 \u0627\u0632 \u06F2\u06F4 \u0633\u0627\u0639\u062A \u062E\u0627\u0631\u062C \u0627\u0632 \u0633\u0631\u0648\u06CC\u0633`,
      summary: `\u0627\u062A\u0627\u0642\u200C\u0647\u0627: ${ooo.map((r) => r.number).join("\u060C ")}. \u0628\u0627 ADR \u0648 \u0627\u0634\u063A\u0627\u0644 \u0641\u0639\u0644\u06CC\u060C \u062F\u0631\u0622\u0645\u062F \u0627\u0632 \u062F\u0633\u062A\u200C\u0631\u0641\u062A\u0647 \u0642\u0627\u0628\u0644 \u062A\u0648\u062C\u0647 \u0627\u0633\u062A.`,
      recommendation: "\u0627\u0648\u0644\u0648\u06CC\u062A\u200C\u062F\u0647\u06CC \u062A\u06CC\u06A9\u062A\u200C\u0647\u0627\u06CC \u0627\u06CC\u0646 \u0627\u062A\u0627\u0642\u200C\u0647\u0627 \u0648 \u062A\u0639\u06CC\u06CC\u0646 \u062A\u0627\u0631\u06CC\u062E \u0628\u0627\u0632\u06AF\u0634\u062A \u0628\u0647 \u0641\u0631\u0648\u0634.",
      confidence: 0.8,
      priority: ooo.length >= 3 ? "high" : "medium",
      estimatedMonthlySaving: Math.round(lostPerMonth),
      evidence: [`ADR \u06F1\u06F4 \u0631\u0648\u0632: ${fmt(adr)}`, `\u0627\u0634\u063A\u0627\u0644 \u06F1\u06F4 \u0631\u0648\u0632: ${fmt(occ * 100)}\u066A`],
      route: "/rooms",
      audienceRoles: ["generalManager", "maintenanceManager", "operationsManager"]
    }
  ];
}
function weekdayOccupancyRule(input) {
  const last28 = input.operations.slice(-28);
  if (last28.length < 21) return [];
  const isWeekend = (day) => {
    const [y, m, d] = day.split("-").map(Number);
    const wd = new Date(Date.UTC(y, m - 1, d)).getUTCDay();
    return wd === 4 || wd === 5;
  };
  const rate = (rows) => rows.reduce((s, o) => s + o.roomsOccupied, 0) / Math.max(1, rows.reduce((s, o) => s + o.roomsAvailable, 0));
  const weekend = rate(last28.filter((o) => isWeekend(o.day)));
  const weekday = rate(last28.filter((o) => !isWeekend(o.day)));
  const gap = (weekend - weekday) * 100;
  if (gap < 12) return [];
  return [
    {
      id: "weekdayOccupancy_gap",
      rule: "weekdayOccupancy",
      category: "revenue",
      title: `\u0641\u0627\u0635\u0644\u0647 ${fmt(gap)} \u0648\u0627\u062D\u062F\u06CC \u0627\u0634\u063A\u0627\u0644 \u0622\u062E\u0631 \u0647\u0641\u062A\u0647 \u0648 \u0631\u0648\u0632\u0647\u0627\u06CC \u0645\u06CC\u0627\u0646\u06CC`,
      summary: `\u0627\u0634\u063A\u0627\u0644 \u0622\u062E\u0631 \u0647\u0641\u062A\u0647 ${fmt(weekend * 100)}\u066A \u0648 \u0631\u0648\u0632\u0647\u0627\u06CC \u0645\u06CC\u0627\u0646\u06CC ${fmt(weekday * 100)}\u066A \u062F\u0631 \u06F4 \u0647\u0641\u062A\u0647 \u0627\u062E\u06CC\u0631.`,
      recommendation: "\u0642\u06CC\u0645\u062A\u200C\u06AF\u0630\u0627\u0631\u06CC \u067E\u0648\u06CC\u0627 \u0648 \u0628\u0633\u062A\u0647\u200C\u0647\u0627\u06CC \u0633\u0627\u0632\u0645\u0627\u0646\u06CC/\u0627\u0642\u0627\u0645\u062A \u0637\u0648\u0644\u0627\u0646\u06CC \u0628\u0631\u0627\u06CC \u0631\u0648\u0632\u0647\u0627\u06CC \u0645\u06CC\u0627\u0646\u06CC \u0647\u0641\u062A\u0647.",
      confidence: 0.68,
      priority: "medium",
      evidence: [`\u0622\u062E\u0631 \u0647\u0641\u062A\u0647: ${fmt(weekend * 100)}\u066A`, `\u0631\u0648\u0632\u0647\u0627\u06CC \u0645\u06CC\u0627\u0646\u06CC: ${fmt(weekday * 100)}\u066A`],
      route: "/reports",
      audienceRoles: ["generalManager", "hotelOwner"]
    }
  ];
}
